name: 'Automate Asana'
description: 'A bot to do all Asana related tasks'
author: Seniorly
branding:
  icon: briefcase
  color: gray-dark
inputs:
  asana_pat:
    description: 'The Asana Personal Access Token'
    required: true
    default: ''
  asana_secret:
    description: 'The Asana Integration Secret'
    required: false
    default: ''
  github_token:
    description: 'The github secret token for accessing PR status etc..'
    default: ''
    required: true
  target:
    description: 'Target sections to move the tasks to'
    default: '{"APPROVED": "Ready For QA", "OPEN": "Code Review", "CLOSED": "Ready for QA", "MERGED": "Live"}'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'